/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.si.tcc.uva.sisedu.telas;

//import java.awt.Dimension;
import com.si.tcc.uva.sisedu.Aluno;
import com.si.tcc.uva.sisedu.dao.AlunoDAO;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lucas
 */
public class Principal extends javax.swing.JFrame {

    ResultSet rs;

    public Principal() throws IOException, SQLException {
        initComponents();
        setLocationRelativeTo(null);
        UpdateTable tab = new UpdateTable();
        tab.setTable();
    }

    public class UpdateTable {

        DefaultTableModel t = new DefaultTableModel();
        // jList1.setModel(m);

        void setTable() throws IOException, SQLException {
            jTable1.setModel(t);

            AlunoDAO alunos = new AlunoDAO();
            List<Aluno> lista = alunos.getListaAlunos();
            t.addColumn("Matricula");
            t.addColumn("Nome");
            t.addColumn("CPF");

            for (int i = 0; i < lista.size(); i++) {
                //System.out.println(lista.toString());
                // m.addElement(lista.get(i));
                t.addRow(new Object[]{lista.get(i).getMatricula(), lista.get(i).getNome(), lista.get(i).getCpf()});
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btExibirDetalhes = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        textNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btConfirmar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btAdicionar = new javax.swing.JRadioButton();
        btModificar = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        textMatricula = new javax.swing.JFormattedTextField();
        btPesquisarAluno = new javax.swing.JButton();
        btExcluirAluno = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btMenuCadCurso = new javax.swing.JMenuItem();
        btMenuCadProf = new javax.swing.JMenuItem();
        btMenuSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btExibirDetalhes.setText("Exibir detalhes");
        btExibirDetalhes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExibirDetalhesActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Historic", 0, 24)); // NOI18N
        jLabel3.setText("SISEDU");

        textNome.setToolTipText("");

        jLabel1.setText("Nome:");

        jLabel2.setText("Matricula:");

        btConfirmar.setText("Confirmar");
        btConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfirmarActionPerformed(evt);
            }
        });

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        buttonGroup1.add(btAdicionar);
        btAdicionar.setText("Adicionar");
        btAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarActionPerformed(evt);
            }
        });

        buttonGroup1.add(btModificar);
        btModificar.setText("Modificar");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        textMatricula.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("####"))));
        textMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textMatriculaActionPerformed(evt);
            }
        });

        btPesquisarAluno.setText("Pesquisar alunos");
        btPesquisarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarAlunoActionPerformed(evt);
            }
        });

        btExcluirAluno.setText("ExcluirAluno");
        btExcluirAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirAlunoActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        btMenuCadCurso.setText("Gerenciar Cursos");
        btMenuCadCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMenuCadCursoActionPerformed(evt);
            }
        });
        jMenu1.add(btMenuCadCurso);

        btMenuCadProf.setText("Gerenciar Professores");
        btMenuCadProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMenuCadProfActionPerformed(evt);
            }
        });
        jMenu1.add(btMenuCadProf);

        btMenuSair.setText("Sair");
        btMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMenuSairActionPerformed(evt);
            }
        });
        jMenu1.add(btMenuSair);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                .addComponent(btPesquisarAluno))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btExibirDetalhes))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(btExcluirAluno)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(55, 55, 55)
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(42, 42, 42))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(btConfirmar)
                                        .addGap(13, 13, 13)))
                                .addComponent(jLabel2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btLimpar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(textMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(300, 300, 300)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btModificar)
                            .addComponent(btAdicionar))
                        .addGap(19, 19, 19)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(textMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btConfirmar)
                            .addComponent(btLimpar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(btAdicionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btModificar)))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btExibirDetalhes)
                        .addGap(44, 44, 44)
                        .addComponent(btPesquisarAluno)
                        .addGap(58, 58, 58)
                        .addComponent(btExcluirAluno)))
                .addGap(192, 192, 192))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btExibirDetalhesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExibirDetalhesActionPerformed
//AdicionarAluno frame = AdicionarAluno(jList1.getSelectedValue());
//System.out.println(jList1.getSelectedValue());
        AlunoDAO alunos = new AlunoDAO();
        int exibir = jTable1.getSelectedRow();

//AlterarAluno alterarAluno;
//System.out.println(jList1.getSelectedIndex());
        try {
            Aluno aluno;
            aluno = alunos.getListaAlunos().get(exibir);

            AlterarAluno alterarAluno = new AlterarAluno(aluno);

            //alterarAluno.setMatricula(aluno.getMatricula());
            //System.out.println(aluno.getMatricula());
            //alterarAluno.setMatricula(1234);
            alterarAluno.setVisible(true);
            alterarAluno.addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosed(WindowEvent e) {
                    UpdateTable tab = new UpdateTable();
                    try {
                        tab.setTable();
                    } catch (IOException ex) {
                        Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (SQLException ex) {
                        Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            });
            // alterarAluno.setMatricula(alunos.getListaAlunos().get(teste).getMatricula());
            // alterarAluno.setCpf(alunos.getListaAlunos().get(teste).getCpf());
            //alterarAluno.setNome(alunos.getListaAlunos().get(teste).getNome());

        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btExibirDetalhesActionPerformed

    private void btConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfirmarActionPerformed
        try {
            Aluno aluno = new Aluno();
            AlunoDAO dao = new AlunoDAO();

            if (btAdicionar.isSelected()) {
                //aluno.setIdaluno(3);
                
                aluno.setNome(textNome.getText());
                System.out.println(textNome.getText());
                AdicionarAluno adicionar = new AdicionarAluno(aluno);
               
                adicionar.setVisible(true);
                            adicionar.addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosed(WindowEvent e) {
                    UpdateTable tab = new UpdateTable();
                    try {
                        tab.setTable();
                    } catch (IOException | SQLException ex) {
                        Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            });

            } else if (btModificar.isSelected()) {
                //aluno.setIdaluno(3);
                
                aluno.setMatricula(Integer.parseInt(textMatricula.getText()));
                dao.buscaAluno(aluno);
                //System.out.println(textNome.getText());
                System.out.println(aluno.getNome());
                System.out.println(aluno.getCpf());
                AlterarAluno alterarAluno = new AlterarAluno(aluno);
               
                alterarAluno.setVisible(true);
                            alterarAluno.addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosed(WindowEvent e) {
                    UpdateTable tab = new UpdateTable();
                    try {
                        tab.setTable();
                    } catch (IOException | SQLException ex) {
                        Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            });

            }
            
            UpdateTable tab = new UpdateTable();
            tab.setTable();
        } catch (Exception ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btConfirmarActionPerformed

    private void btMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMenuSairActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_btMenuSairActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        textMatricula.setText("");
        textNome.setText("");
    }//GEN-LAST:event_btLimparActionPerformed

    private void btAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btAdicionarActionPerformed

    private void btMenuCadProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMenuCadProfActionPerformed
        AdicionarProfessor frame = new AdicionarProfessor();

        frame.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btMenuCadProfActionPerformed

    private void btMenuCadCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMenuCadCursoActionPerformed
        AdicionarCurso frame = new AdicionarCurso();

        frame.setVisible(true);
    }//GEN-LAST:event_btMenuCadCursoActionPerformed

    private void textMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textMatriculaActionPerformed

    private void btPesquisarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarAlunoActionPerformed

        PesquisarAluno pesquisar = null;
        try {
            pesquisar = new PesquisarAluno();
        } catch (IOException | SQLException e1) {
            // TODO Auto-generated catch block
            e1.printStackTrace();
        }

        pesquisar.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_btPesquisarAlunoActionPerformed

    private void btExcluirAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirAlunoActionPerformed
        try {
            ExcluirAluno excluirAluno = new ExcluirAluno();
            excluirAluno.setVisible(true);
            excluirAluno.addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosed(WindowEvent e) {
                    UpdateTable tab = new UpdateTable();
                    try {
                        tab.setTable();
                    } catch (IOException | SQLException ex) {
                        Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
            );
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btExcluirAlunoActionPerformed

                    /**
                     * @param args the command line arguments
                     */
                    public static void main(String args[]) {
                        /* Set the Nimbus look and feel */
                        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
                        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
                         */
                        try {
                            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                    break;
                                }
                            }
                        } catch (ClassNotFoundException ex) {
                            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                        } catch (InstantiationException ex) {
                            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                        } catch (IllegalAccessException ex) {
                            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                        }
                        //</editor-fold>
                        //</editor-fold>
                        //</editor-fold>
                        //</editor-fold>

                        /* Create and display the form */
                        java.awt.EventQueue.invokeLater(new Runnable() {
                            public void run() {
                                try {
                                    new Principal().setVisible(true);
                                } catch (IOException ex) {
                                    Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                                } catch (SQLException ex) {
                                    Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                                }
                            }
                        });
                    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btAdicionar;
    private javax.swing.JButton btConfirmar;
    private javax.swing.JButton btExcluirAluno;
    private javax.swing.JButton btExibirDetalhes;
    private javax.swing.JButton btLimpar;
    private javax.swing.JMenuItem btMenuCadCurso;
    private javax.swing.JMenuItem btMenuCadProf;
    private javax.swing.JMenuItem btMenuSair;
    private javax.swing.JRadioButton btModificar;
    private javax.swing.JButton btPesquisarAluno;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JFormattedTextField textMatricula;
    private javax.swing.JTextField textNome;
    // End of variables declaration//GEN-END:variables
}